server:
  port: 8089

spring:
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_manager?serverTimezone=Asia/Seoul
    username: root
    password: 1234
--- #테이블 자동 생성
#spring:
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
--- #Naver OAuth 설정
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_LOGIN_ID}
            client-secret: ${NAVER_LOGIN_SECRET}
            redirect-uri: http://localhost:8089/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
          google:
            client-id: ${GOOGLE_LOGIN_ID}
            client-secret: ${GOOGLE_LOGIN_SECRET}
            redirect-uri: http://localhost:8089/login/oauth2/code/google
            scope: profile, email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
---
spring:
  profiles:
    include: oauth