server:
  port: 8089

spring:
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_manager?serverTimezone=Asia/Seoul
    username: root
    password: 1234